# 第五章 异常与错误处理

异常实际上是Python这门编程语言里许多核心机制的基础。

## 5.1 基础知识

### 5.1.1 优先使用异常捕获

```python
def incr_by_one(value):
    """对输入整数加1，返回新的值

    :param value: 整型，或者可以转成整型的字符串
    :return: 整型结果
    """
    if isinstance(value, int):
        return value + 1
    elif isinstance(value, str) and value.isdigit():
        return int(value) + 1
    else:
        print(f'Unable to perform incr for value: "{value}"')
```

在`incr_by_one()`函数里，因为参数value可能是任意类型，所以我写了两个条件分支来避免程序报错：

1. 判断仅当类型是`int`时才执行加法操作；

2. 判断仅当类型是`str`, 同时满足`.isdigit()`方法时才进行操作。

这几行代码代表了一种编程风格：LBYL(look before you leap) 翻译为“三思而后行”。

就是在执行一个可能会出错的操作时，先做一些关键的条件判断，仅当条件满足时才进行操作。

LBYL 之外，还有另一种与之形成鲜明对比的风格：EAFP（easier to ask forgiveness than permission), 可直译为“获取原谅比许可简单”。

**EAFP**

EAFP 指不做任何事前检查，直接执行操作，但在外层用try来捕获可能发生的异常。

如果遵循EAFP风格，`incr_by_one()`函数可以改成下面这样：

```python
def incr_by_one(value):
    """对输入整数加1，返回新的值

    :param value: 整型，或者可以转成整型的字符串
    :return: 整型结果
    """
    try:
        return int(value) + 1
    except (TypeError, ValueError) as e:
        print(f'Unable to perform incr for value: "{value}", error: {e}')
```

EAFP 编程风格更为简单直接，总是直奔主流程而去，把意外情况都放在异常处理`try/except`块内消化掉。

哪种编程风格更好？

我只能说，整个Python社区明显偏爱基于异常捕获的EAFP风格。

原因：略

### 5.1.2 try 语句常用知识

01. 把更精确的except语句放在前面

```python
#BaseException是一切异常类的父类，甚至包括 KeyboardInterrupt 异常
>>> issubclass(Exception, BaseException)
True
>>> issubclass(LookupError, Exception)
True
>>> issubclass(KeyError, LookupError)
True
```

上面的代码展示了一条异常类派生关系：

BaseException -> Exception -> LookupError -> KeyError

如果一个try 代码块里包含多条except，异常匹配会按照从上而下的顺序进行。这时，假如你不小心把一个比较模糊的父类异常放在前面，就会导致在下面的except永远不会被触发。

```python
def incr_by_key(d, key):
    try:
        d[key] += 1
    except Exception as e: ➊
        print(f'Unknown error: {e}')
    except KeyError:
        print(f'key {key} does not exists')
```

KeyError 分支下的内容永远不会被执行

02. 使用else 分支

```python
#同步用户资料到外部系统，仅当同步成功时发送通知消息
sync_succeeded = False
try:
    sync_profile(user.profile, to_external=True)
    sync_succeeded = True
except Exception as e:
    print("Error while syncing user profile")
if sync_succeeded:
    send_notification(user, 'profile sync succeeded')
```


```python
try:
    sync_profile(user.profile, to_external=True)
except Exception as e:
    print("Error while syncing user profile")
else:
    send_notification(user, 'profile sync succeeded')
```
